# /usr/share/doc/lighttpd-doc/proxy.txt

server.modules   += ( "mod_proxy" ) #, "mod_proxy_core", "mod_proxy_backend_http" )

$HTTP["host"] =~ "^mail\." {
  $HTTP["url"] =~ "^/\.well-known/acme-challenge" {
    server.document-root = "/var/www"
  } else $HTTP["url"] =~ "^/headers" {
    proxy.server = (
      "" => ((
        "host" => "httpbin.org",
        "port" => 80
      ))
    )
    proxy.forwarded = (
      "for" => 1,
      "proto" => 1
    )
  } else $HTTP["url"] =~ "" {
    proxy.server = (
      "" => ((
        "host" => "localhost",
        "port" => 9080
      ))
    )
    proxy.forwarded = (
      "for" => 1,
      "proto" => 1
    )
  }
}
